[package]
edition = "2024"
name = "db"
version = "0.1.0"

[dependencies]
db-core = { path = "../db-core" }
db-impl-mock = { path = "../db-impl-mock" }
db-impl-postgres = { path = "../db-impl-postgres" }
model = { path = "../model" }

[lints]
workspace = true
