[package]
name = "db-core"
version = "0.1.0"

edition = "2024"
publish = false

[dependencies]
model = { path = "../model" }

async-trait.workspace = true
miette.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
